name: CI -> Deploy to Prod
on:
  push:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Here is the deployment action
      - name: Upload from docs via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: q1.cityhost.com.ua
          user: chc214115c_github
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: "./docs"
          remote_dir: "./"
          delete: "true"
          max_retries: "7"